# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zfw/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zfw/nixos/home";
      fsType = "zfs";
    };

  fileSystems."/home/vh" =
    { device = "zfw/nixos/vh";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F253-31F3";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c28efdb3-d6ba-47d6-87a2-1c04a7272514"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
